Unwrap all i18n calls
Automattic/crowdsignal-forms pull request #1
Opened 2020-11-09 23:10 UTC by CGastrell

This PR just unwraps all our i18n calls so we use the `@wordpress/i18n` directly.

Once this is merged, next releases should be able to export our translatable strings to the .pot file and get into the wpcom translations flow/cron (ref: p1604357927213600-slack-C02ER2E0Z)

## Test instructions

Checkout and run:

  - `npm run lint:all`
  - `make client`

2020-11-09 23:11 UTC, CGastrell commented
I should remove the now unused `lib/i18n` file

2020-11-13 09:29 UTC, ice9js requested changes
Nice! I don't think we need to be translating font names though 😄

2020-11-13 09:29 UTC, ice9js commented on client/blocks/applause/sidebar.js
> +import { PollStatus } from './constants';
The world is a better place now!

2020-11-13 09:29 UTC, ice9js commented on client/blocks/poll/sidebar.js
> +							label: __( 'Alegreya Sans', 'crowdsignal-forms' ),
Why are we translating font names 👽  ? Let's remove this while we're at it.

2020-11-17 18:15 UTC, ice9js approved these changes
Nice! Thanks for cleaning up the old lib as well ;)

2020-11-17 18:37 UTC, merged