Feedback sidebar section changes
Automattic/crowdsignal-forms pull request #100
Opened 2021-04-27 19:19 UTC by CGastrell

This PR

  - changes the URL to crowdsignal.com so it doesn't mutate to that of the results.
  - removes the media upload section for the trigger button

## Test instructions
Checkout and `make client`. Insert all our blocks on a post. The link to Crowdsignal on the "Results" section of the sidebar should always point to crowdsignal.com

On the Feedback block sidebar "Feedback button" section, there should be no media upload option, only the shadow toggle.

2021-04-28 12:16 UTC, digitalwaveride commented
Thanks Christian for going after this! 🙏 


- Editor View: When the card is open, the cursor above the button should be "text" so users get a hint that the text is editable. (when the card is closed, it should be "pointer" of course)

- The styling of the buttons (text styling) does currently differ in the editor and published view
![image](https://user-images.githubusercontent.com/5120357/116396743-06214780-a826-11eb-82ae-41e76f0d4f53.png)

- Published View: The "close" button "x" is not yet properly implemented - currently there Is just a color change on the button bg, which would make no sense in that context. 
![image](https://user-images.githubusercontent.com/5120357/116396866-27823380-a826-11eb-9600-dcdaa958aaf0.png)
We should keep the color of the button and of course the size.
In order to make the button less competitive to the "Submit" button that might be just a few centimeters above it, we could experiment to give it a: 
opacity: 0.7;

- The Styling of the feedback button
As discussed in our call, for the button styling we would need to work with a mix of "dynamic" style elements inherited by the theme, and a few fixed ones.

FIXED:
-> font-size: 16px;
-> line-height: 150%;
-> text-align: center;
-> padding: 12px 16px;

INHERITED FROM THE THEME:
from the "button block" styling:
-> font-color
-> color
-> font-family
-> font-weight
-> border-radius
-> text-transform
-> text-decoration


- Published View: Noticed that if you use emojis in the text, in the published view the empty space after an emoji is ignored  
![image](https://user-images.githubusercontent.com/5120357/116401474-94e49300-a82b-11eb-9060-b3377eff2446.png)

2021-04-28 13:34 UTC, digitalwaveride commented
Regarding the design of the Close state button ... it could look like this, the label "Close" with a X icon: 

![image](https://user-images.githubusercontent.com/5120357/116412348-e34b5f00-a836-11eb-956a-36a500e277ac.png)

2021-04-28 20:01 UTC, ice9js requested changes
I noticed we can remove a few more things and I'm not sure I understand how using Gutenberg's `<Button>` for the toggle is helpful for our case?

2021-04-28 20:01 UTC, ice9js commented on client/blocks/feedback/edit.js
> -import { getStyleVars, getTriggerStyles } from './util';
If `getTriggerStyles` isn't used anywhere anymore (which I think it shouldn't be at this point) let's remove it.

2021-04-29 06:42 UTC, ice9js approved these changes
>NOTE 2: a cascade of styles is applied to our buttons, we might want to improve this in the future. Right now the button is wrapped with wp-block-button, inherits from wp-block-button__link and is customized with crowdsignal-forms-feedback__trigger and crowdsignal-forms-feedback__feedback-button

Yeah, we'll probably want to grab these styles together with everything else eventually or we end up with the same issue. Good enough for now though.

Just one linter error remaining.

2021-04-29 14:08 UTC, digitalwaveride requested changes
Thanks Christian for all the fixes! Nice! Looks much better!

We are close! Two things for fine-tuning:

- The Close button state, could we add there the "X" icon instead of the font letter?
![image](https://user-images.githubusercontent.com/5120357/116563794-a8176180-a904-11eb-8040-8f724473455e.png)

- The Button Styling
It seems that it currently mirrors completely the "Submit Button", only the hover state is for me missing, but does not apply yet the fixed "hard-coded" css elements. 
![image](https://user-images.githubusercontent.com/5120357/116563885-c2513f80-a904-11eb-8b90-494036244b7f.png)

![image](https://user-images.githubusercontent.com/5120357/116564115-f7f62880-a904-11eb-8c18-5cfa4d68fe09.png)

2021-04-29 17:48 UTC, digitalwaveride approved these changes
👍

2021-04-29 17:58 UTC, merged