Fix feedback block editor overlay on the full site editor
Automattic/crowdsignal-forms pull request #157
Opened 2021-07-16 22:47 UTC by ice9js

This patch fixes the issue with the feedback block editor overlay being offset incorrectly inside the full site editor by checking if the block is rendered inside an iframe.

Before:

![Screen Shot 2021-07-17 at 12 41 40 AM](https://user-images.githubusercontent.com/8056203/126015244-3d4eea5c-1172-45a8-b75f-e2a68c0fa293.png)

After:

![Screen Shot 2021-07-17 at 12 42 03 AM](https://user-images.githubusercontent.com/8056203/126015240-36f4043c-ad25-431c-bf56-cae06d971865.png)

# Testing

Make sure you're testing on WP `trunk` and select a theme which has FSE support.
Verify that when adding the feedback block in side of the full site editor, the overlay is rendered correctly when the block is selected.
Similarly, verify that the overlay still displays correctly on the regular poll editor which doesn't have the iframe.

2021-07-19 14:30 UTC, CGastrell commented
I'm having this issue where I inserted the feedback button block on the body of the page, yet the footer takes precedence on the z-index. So, when hovering, the footer will display this outline and if I click, of course, the focus goes into the footer, not the block.

![image](https://user-images.githubusercontent.com/157240/126176106-7c67b4f0-a275-43ad-a966-2149fa16b6cc.png)

2021-07-19 14:33 UTC, CGastrell requested changes
Check on the above comment to see some weird behavior (actually not that weird)

2021-07-21 17:52 UTC, ice9js commented
I bumped up the z-index value - since we're positioning it manually anyway, the old comment doesn't apply anymore.

2021-07-22 08:45 UTC, digitalwaveride approved these changes
Worked for me as advertised!
![image](https://user-images.githubusercontent.com/5120357/126612358-7bee86da-84f3-49a2-8775-b6df7cea8970.png)

🚀

2021-07-22 13:17 UTC, CGastrell approved these changes
Working fine now :shipit:

2021-07-22 13:58 UTC, merged