Fix broken isWidgetEditor test.
Automattic/crowdsignal-forms pull request #173
Opened 2021-09-15 07:08 UTC by yansern

## Description

Fixes the `isWidgetEditor` checking.

## Test Instructions

1. Go to Customize > Widgets.
2. Add "Feedback Button" block.
3. It should not show the error 'This block has encountered an error and cannot be previewed.' and cannot be previewed'.

Fixes https://github.com/Automattic/wp-calypso/issues/55808

2021-09-15 14:18 UTC, ice9js requested changes
The updated condition works, thank you!  
There's a few more issues we need to address, also `npm run lint:js` is failing.

The block still comes up with _this block cannot be rendered_ message. To fix it, the following condition needs to be added [here](https://github.com/Automattic/crowdsignal-forms/blob/master/client/blocks/feedback/edit.js#L217):

```
useLayoutEffect( () => {
	if ( isWidgetEditor ) {
		return;
	}
	...
```

I also noticed another issue, perhaps more significant... The block is still rendered with incorrect positioning and missing styles. It seems that the customizer is missing `.editor-styles-wrapper` which I believe is what most editor style overrides are supposed to be based on, not just in our block. Hence this is maybe something that needs to be addressed in core?

Otherwise we'll need to find an alternative selector for [these styles](https://github.com/Automattic/crowdsignal-forms/blob/master/client/blocks/feedback/edit.scss#L54).

![Screen Shot 2021-09-15 at 4 16 07 PM](https://user-images.githubusercontent.com/8056203/133450396-80dc36ec-752e-4aea-95d0-3da040bcba24.png)

On a side note, since the customizer sidebar _is immune_ to any theme styles hence the block has a different appearance in the sidebar than on the preview but maybe that's not an issue because well... there's the preview?

2021-09-22 07:28 UTC, yansern commented
Thanks @ice9js. I'm back and I'm looking at this now.

2021-09-23 10:21 UTC, yansern commented
Alright, CSS fixes are also in now.

![image](https://user-images.githubusercontent.com/1287077/134491337-e1d67081-b8ab-4c6a-a3d5-962daaad1de2.png)

2021-09-23 10:50 UTC, ice9js approved these changes
Nice! Works for me, thanks again for picking this one up ;)

2021-09-23 10:50 UTC, merged