add/crowdsignal-embed block
Automattic/crowdsignal-forms pull request #222
Opened 2022-05-13 15:00 UTC by TheSteveK

This is a new block based off the core embed block specially designed to embed Crowdsignal surveys.  Links and buttons have been tailored to Crowdsignal surveys.  The block will also only accept known Crowdsignal domains to avoid confusion.

The core functionality of the embed block largely remains the same and the final result is output to the format from the embed block so the native embed process takes over the duties of displaying the embed in the published page.

There is a limitation in the core embed block where the preview only renders to a certain height in the editor, that also exists in this block.

Testing instructions:
Checkout branch and build the plugin.

Verify "Survey" item exists in the block library and shows up when you search for a block via typing / or hitting the inline + button

Try embedding a non-crowdsignal URL like YouTube, verify the error
Try putting in random garbage text, verify the error
Try a valid Survey URL from the survey's sharing settings, confirm the embed preview loads
Preview the page, verify the embed shows up.

2022-06-29 09:14 UTC, digitalwaveride commented
Nice Steve!!! So great to see this block! 🥳 

Embedding functionality worked for me! 👍 


### Some design finetuning:

This is what I currently see:

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/5120357/176395405-8030e0b5-3b21-4d37-aa3e-727076b5bc9d.png">

This is the [Figma design](https://www.figma.com/file/Y179jGRPQMN4UjydcQ7784/Survey-Embed-Block?node-id=60%3A197):

![image](https://user-images.githubusercontent.com/5120357/176397627-919a83d1-80b1-42f4-bef7-c63f34cb7306.png)


- [ ] The block icon is mixed up, that one is the quiz icon

- [ ] The block description is still missing

![image](https://user-images.githubusercontent.com/5120357/176396671-60969617-6772-48bd-80f9-55630457bf55.png)

- [ ] The text above the input field: "Paste a link to the survey you want to display on your site." is missing.
- [ ] The link text below the input field should be more "proactive -> create!": Create a new survey
- [ ] The spacings need to be finetuned
![image](https://user-images.githubusercontent.com/5120357/176398573-af19b2bc-934d-4966-8243-c23cd240ad3b.png)

Please feel free to copy paste stuff from the basic Crowdsignal embed block:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/5120357/176399505-9bcd98fe-07c8-43cd-9c40-484e67a237b6.png">


- [ ] The Crowdsignal logo can be a bit smaller -> 40px


---

And one additional thing... let's discuss if it is a bigger issue to implement:


### The settings sidebar sections are still missing:

The reason why we need these links is that users might forget where they can find the results etc... so even if these links just point to the dashboard, that should be helpful.


![image](https://user-images.githubusercontent.com/5120357/176396637-f3ebb879-9b38-4e58-a88d-7c913353f2ae.png)


We are close Steve 🚀 ! Thank you!

2022-06-29 09:14 UTC, digitalwaveride requested changes
see comment above

2022-06-29 20:22 UTC, TheSteveK commented
@digitalwaveride  I think I got everything addressed in the latest commit.  A couple of notes.  The sidebar description and the description that shows in the block picker are the same so I went with the text you provided.  

Also, we already have a component we use in our other blocks that shows that upgrade message.  I used that so the formatting is a bit different than what your figma shows.  Also note, to see it, you'll need to change yourself to a free account.

2022-06-30 08:18 UTC, digitalwaveride commented
@TheSteveK hmn... can't see the changes... but also can't see commits in the activity feed here... 🤔

2022-06-30 19:39 UTC, jcheringer requested changes
Thanks for taking care of this Steve.
I added a few comments that could help us keep the code simpler and/or consistent with what we have on our code base.
Please let me know if you have any questions.

2022-06-30 19:39 UTC, jcheringer commented on client/blocks/cs-embed/embed-preview.js
> +	// const html = '<p> this is placeholder html </p>';
Could we remove this comment? 🙂

2022-06-30 19:39 UTC, jcheringer commented on client/blocks/cs-embed/sidebar.js
> +					</a>
When creating a concatenated string, to make it translatable, there is this helper [createInterpolateElement](https://github.com/WordPress/gutenberg/tree/trunk/packages/element#createInterpolateElement) we need to use.
If you need some examples on how to use it, you can find some [here](https://github.com/search?q=org%3AAutomattic+createInterpolateElement&type=code).

Another thing I didn't understand well is why we need the `typeTextPlural` as an attribute/variable. 
Couldn't we just inline the string?

2022-06-30 19:39 UTC, jcheringer commented on client/blocks/cs-embed/sidebar.js
> +					</a>
The same situation to use the `createInterpolateElement` helper.

2022-06-30 19:39 UTC, jcheringer commented on client/blocks/cs-embed/toolbar.js
> +// import { edit } from '@wordpress/icons';
Could we remove the comment?

2022-06-30 19:39 UTC, jcheringer commented on client/components/icon/quiz.js
> +function Survey() {
What about changing the function name to comply with the filename?

2022-07-01 13:46 UTC, TheSteveK commented
I've commited changes based on your request @jcheringer  give it another spin :)

2022-07-01 15:34 UTC, jcheringer approved these changes
LGTM!

2022-07-01 18:25 UTC, merged