Add free signal notices
Automattic/crowdsignal-forms pull request #78
Opened 2021-04-07 21:53 UTC by CGastrell

This PR adds the notices we use for exhausted signals and errors while trying to sync to the Crowdsignal platform

NOTE: the notices look much better with #77 applied.

## Test instructions
### If you want to include the mentioned dependency:
```
git fetch
git checkout fix/signal-warning-layout && git pull
git checkout add/free-and-signal-notices
git merge fix/signal-warning-layout
```
Those steps will ask you for a commit message, just save and close.

Otherwise, just checkout the branch and run `make client`

Use a free account with signals exhausted.

Insert a Feedback block. You should see the signal warning when you open the popup.

Disconnect, then make a change on the Feedback block settings. After 3 attempts (around 10-15 seconds) the sync error should appear on the popup. Connect again and hit the "Retry" button. Confirm your changes successfully synced by checking your dashboard.

2021-04-08 19:21 UTC, digitalwaveride requested changes
Very nice Christian!
The API connection etc. seem to work for "out of signals" and "no connection" 👍 

Two little things I noticed:

- There is a little glitch in the styling of the notification, the text colors or in parts "white":

![image](https://user-images.githubusercontent.com/5120357/114082923-a5e65800-98ae-11eb-82ce-f9ddf454b6b3.png)

![image](https://user-images.githubusercontent.com/5120357/114083428-3e7cd800-98af-11eb-9a2f-ac46ebd356aa.png)

![image](https://user-images.githubusercontent.com/5120357/114083514-5a807980-98af-11eb-8187-20b73983705d.png)

- If possible, the notifications should be outside of the card, the "popup UI content". The notifications are part of the editor UI like the toolbar, and should be below the toolbar and above the card (the red line), similar how we handle it for the NPS block:

![image](https://user-images.githubusercontent.com/5120357/114083768-b3501200-98af-11eb-89de-aa6d023a4a1b.png)

2021-04-09 09:50 UTC, digitalwaveride commented
Thank you Christian!!! Awesome that things worked out with the notification banner placement! Nice! 😍



On more round of fine-tuning, but we are close:

### Colors 

![image](https://user-images.githubusercontent.com/5120357/114161366-42007580-9928-11eb-80f6-71d3ae0aac53.png)

### Icon Size

Could we give the icons the same size (the bigger one), could we use the same icon type? Whatever the "standard" Gutenberg one would be.
![image](https://user-images.githubusercontent.com/5120357/114161735-b509ec00-9928-11eb-9683-d58f5edcbf22.png)

### Spacing & Alignment

Not sure if you have here some impact on the toolbar placement, but it would be super nice, if we could adjust this a bit:

![image](https://user-images.githubusercontent.com/5120357/114162122-1762ec80-9929-11eb-9112-3b0b83fe360e.png)


### Three row signals notification banner -> any chance to bring it into two?

![image](https://user-images.githubusercontent.com/5120357/114162698-a4a64100-9929-11eb-8618-e90e35ffa760.png)

2021-04-09 16:43 UTC, CGastrell commented
All things noted, but these are the default notices we're using. Shall we need to address design issues on them, I'd like to do it on a separate card/PR. I do agree these things need to be fixed, but let keep things moving.

I created c/KtcbhyoS-tr/1284-improve-our-notice-warnings-design to keep track of this

2021-04-09 17:20 UTC, digitalwaveride approved these changes

2021-04-09 17:50 UTC, merged