Remove icons SVG fills
Automattic/crowdsignal-forms pull request #98
Opened 2021-04-26 19:34 UTC by CGastrell

Removing the `fill` property allows for CSS to rule over it, making those icons look more *aligned* with the rest out there.

Note that I couldn't achieve the same with the Feedback Button icon, since the chat balloon is not `fill`ed, it's merely a `stroke`d path. Not sure we can get to the same icon where the `fill` defines the color of the balloon outline.

**Before:**
![fills-before](https://user-images.githubusercontent.com/157240/116139901-f03c4700-a6ac-11eb-8267-81e7378e5fab.gif)

**After:**
![fills-after](https://user-images.githubusercontent.com/157240/116139920-f6cabe80-a6ac-11eb-8ade-dc24fc323042.gif)

## Test instructions
Checkout and `make client`. Edit a post, type `/crowd` to get all of our blocks on the popup list. Hover the blocks in the list, the icons should get the same color of the text.

Check that Applause and Vote icons preserve functionality and styling on the frontend (Applause allows for a lot of color customization)

2021-04-27 02:02 UTC, digitalwaveride approved these changes
🚀

2021-04-27 08:12 UTC, ice9js requested changes
I'd say let's just remove the `fill` attributes although it looks like you just replaced some of the icons entirely?

In general we should maybe reconsider how we generate these... as in how we can actual export SVGs optimized for web use. The default exports are a mess.

2021-04-27 08:12 UTC, ice9js commented on client/components/icon/applause.js
> +				fill=""
Why not just omit the attribute entirely?

2021-04-29 11:18 UTC, ice9js approved these changes
👍

2021-04-29 14:09 UTC, merged